### ISSUE TITLE
Opening the GUI doesn't work!

### ISSUE THREAD

**Issue by b9Joker108** [sagar040/proot-distro-nethunter#4]
Thank you so much for this Bash script!

I had used the official git clone a few days ago, but it wasn't updating packages, so uninstalled it.

Your script worked beautifully. I just have one reservation and bug, I tried this section, but it doesn't work:

https://github.com/sagar040/proot-distro-nethunter?tab=readme-ov-file#accessing-the-nethunter-gui

Also, you haven't updated the version to 1.5 in the version listing tag on the right hand side of the screen. Just to let you know.

**Comment by sagar040** [comment]
please elaborate the exact issue/errors you're facing while using those commands you have mentioned [here](https://github.com/sagar040/proot-distro-nethunter?tab=readme-ov-file#accessing-the-nethunter-gui).

You can DM me at [Reddit](https://www.reddit.com/user/sagarbiswas1).

**Comment by b9Joker108** [comment]
Hi, thanks for responding. I tried to post the following message as a direct message on Reddit, but it wouldn't send. Reddit said it had an illegal link!

This is what I did in the terminal:

https://pasteboard.co/DqVzMUtPOZbZ.jpg

I did which bash, which sh and which zsh and got:
/usr/bin/bash, /usr/bin/sh and /usr/bin/zsh

This is my path:

echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/data/data/com.termux/files/usr/bin:/system/bin:/system/xbin:/snap/bin

I am using shebang lines: #!/usr/bin/env bash,  #!/usr/bin/env sh and #!/usr/bin/env zsh, and changed these as appropriate in your kgui and xstartup scripts. For the kgui script to execute with just mentioning its name in the terminal, I thought that it would be in the .bashrc file, but it isn't, how were you trying to make it work?

I also tried to create a script to launch a GUI:

https://pastebin.com/70th9PfJ

But when I tried to execute it, I got this error output:

https://pastebin.com/xKkQ599k

I would really appreciate your help getting a GUI going.

**Comment by sagar040** [comment]
Fixed some issues in Version 1.6
