### ISSUE TITLE
Failed to retrieve SHA256 checksum.

### ISSUE THREAD

**Issue by theteleporter** [sagar040/proot-distro-nethunter#5]
I'm installing the distro but I'm encountering an error when retrieving SHA256 checksum, 
Here are my logs

>>>>>>> Installing required packages >>>>>>>
Hit:2 https://grimler.se/termux/termux-main stable InRelease
Hit:1 https://turdl.kcubeterm.com tur-packages InRelease
Hit:3 https://grimler.se/termux/termux-x11 x11 InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
proot-distro is already the newest version (4.17.2).
curl is already the newest version (8.10.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
>>>>>>> Retrieving SHA256 checksum >>>>>>>
Error: Failed to retrieve SHA256 checksum. Exiting.

**Comment by sagar040** [comment]
Sorry user. This is happening because nethunter has changed there repo structure and file names. I haven't updated the script with the new urls yet.
Wait for some days I will update it ❤️.

**Comment by theteleporter** [comment]
Okay cool

**Comment by Antoinecim** [comment]
I have the  same  problem.. With the SHA256  ... its not fixed  yet?

**Comment by theteleporter** [comment]
> I have the  same  problem.. With the SHA256  ... its not fixed  yet?
> 
> 
The repo owner has said that in a few days time, he'll fix the issue, it's something to do with the nethunter changing the repo structure and file names, I think.

**Comment by theteleporter** [comment]
> @theteleporter @Antoinecim 
> The issue has been resolved in [version 1.8](https://github.com/sagar040/proot-distro-nethunter)
> See the change logs : [https://github.com/sagar040/proot-distro-nethunter?tab=readme-ov-file#change-logs](https://github.com/sagar040/proot-distro-nethunter?tab=readme-ov-file#change-logs)

Niiice! 😌, appreciate it man 🙂‍↕️
